### ISSUE TITLE
is push-dns necessary ?

### ISSUE THREAD

**Issue by nlm** [scaleway-community/scaleway-openvpn#1]
In the config files tcp443 and udp1194, the 8.8.8.8 and 8.8.4.4 DNS are pushed.

1) It is probably not necessary to push the DNS, as it is often used to give access to "private" domain names, and in this case, there are none. The local client DNS will be used and will be equivalent

2) If the image is designed to give restricted access to the machine services, then any DNS server that is already configured on the client is fine.

3) If it is designed to avoid DNS-based spying, it should include a dns-server (best) or at least a dns-forwarder to online-labs customers DNS servers, and push dns+routes to the openvpn server private IP

**Comment by multun** [comment]
c9d0e0f somehow implements a fix:
 * The image runs an unbound forwarder to scaleway's DNS (or any other, scaleway is the default)
 * The address of this resolver is pushed to the client
