### ISSUE TITLE
HTTPS tunnel

### ISSUE THREAD

**Issue by marvinroger** [scaleway-community/scaleway-openvpn#21]
The current implementation of the Scaleway OpenVPN listens on TCP 443, which is, I presume, in order to bypass corporate firewalls. The problem is that a lot of firewalls use deep packet inspection (DPI) to check if the traffic is *genuine*. And obviously, in our case, it is not.

A simple solution to this problem is to tunnel the connection through an HTTPS tunnel, using `stunnel4`. It is as simple as:

```
cert = /etc/stunnel/stunnel.pem

[openvpn-localhost]
accept = 443
connect = 127.0.0.1:TCP_PORT_OF_OPENVPN
```

The downside is this would require a client to also have `stunnel`, as the 443 port would not then be a valid OpenVPN port to connect to. The benefit is this is completely stealth. So I guess this should be configurable.

**Comment by moul** [comment]
Hi @marvinroger,

I like the idea, however as you said it will require more dependencies from the client, so we should be able to toggle this feature on-demand or better to have both services running at the same time

Maybe we can choose one port for stunnel and the other one for direct openvpn ?

**Comment by marvinroger** [comment]
I just took a look at the possibilities, and there is an even better one. There is an option named `port-share` that allows any non-OpenVPN traffic to be redirected to another port:

* We keep the current TCP 443 listening, but we add a line in the config file:

```
port-share 127.0.0.1 STUNNEL_PORT
```

* The stunnel config would look like so:

```
cert = PATH_TO_CERT

[openvpn-localhost]
accept = 127.0.0.1:STUNNEL_PORT
connect = 127.0.0.1:443
```

This way, the `STUNNEL_PORT` would only be bound to `127.0.0.1` and OpenVPN would receive requests on `TCP 443` and handle it normally if this is OpenVPN traffic, or redirect to the stunnel server if this is HTTPS traffic. So this would be perfectly transparent!

**Comment by moul** [comment]
Very interesting, we definitely need to test it and implement it in the image if it works as expected

**Comment by marvinroger** [comment]
I'll test and report back. :wink:

**Comment by marvinroger** [comment]
Alright, I tested and it works perfectly. Step by step after image creation:

* `apt-get install stunnel4`
* stunnel4 needs the key and the cert in a single file: 
```
cat /etc/openvpn/key.pem /etc/openvpn/cert.pem >> /etc/stunnel/stunnel.pem
```
* Content of /etc/stunnel/stunnel.conf:
```
cert = /etc/stunnel/stunnel.pem

[openvpn-localhost]
accept = 127.0.0.1:442
connect = 127.0.0.1:443
```
* We need to enable stunnel which is disabled by default:
```
sed -i s/ENABLED=0/ENABLED=1/g /etc/default/stunnel4
```
* In /etc/openvpn/tcp443.conf, add:
```
port-share 127.0.0.1 442
```
* Restart services: `service openvpn restart` and `service stunnel4 restart`

I am not familiar enough with your infrastructure to fill a PR, so I'll let you do it properly.

**Comment by moul** [comment]
> Alright, I tested and it works perfectly

Can you confirm it still works with the old method, using only OpenVPN as client ?

> I am not familiar enough with your infrastructure to fill a PR, so I'll let you do it properly.

Ok no problem, we will add your GitHub handle in the commit message for all your investigation time

**Comment by marvinroger** [comment]
I do, there is no breaking change.

Thanks for your quick answers!

**Comment by moul** [comment]
perfect, I created a PR with all your stuff, we still need to test it before releasing the new image
