### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by psphacker06** [scaleway-community/scaleway-openvpn#24]
When I connect to the ovpn file given to me in the MOTD I get no internet access. Tried on multiple computers with the same results. Anything off the top your head I can try to make it work? Seems like a  firewall issue?

**Comment by psphacker06** [comment]
Its a clean install that is having the issue. Help is appreciated.

**Comment by QuentinPerez** [comment]
Hi @psphacker06 

Thank you for your feedback, I succeeded to reproduce your problem on a VPS.
@bchatelard do you know if there is firewall issue on VPS ?

We will come back to you as soon as possible ☺️

**Comment by QuentinPerez** [comment]
@bchatelard 's solution

Can you try the following commands on your vpn server ?
```console
root@scw:~# scw-sync-kernel-modules
root@scw:~# depmod -a
root@scw:~# service iptables-persistent restart
```
Let me know if you need anything else ?

**Comment by psphacker06** [comment]
@QuentinPerez & @bchatelard 
Yup that fixed it. Thank you so much. Are you thinking about updating the image? I plan on using it a lot and would be less of a hassle if it would automatically download + install a fixed version.

**Comment by QuentinPerez** [comment]
Yes, we will update the image as soon as possible 😊

**Comment by psphacker06** [comment]
When should I expect it?

**Comment by QuentinPerez** [comment]
Hi @psphacker06,

A new image is available with the fix 😉
