### ISSUE TITLE
Problem to access simpleHTTP conf files after reboot

### ISSUE THREAD

**Issue by Digital14** [scaleway-community/scaleway-openvpn#27]
Hi,
I am contacting you because I have an issue with the SimpleHTTP server.
I ran a default setup and it was working until I rebooted the server.
After an installation I can access the configuration file on http://IP:8000/UUID/file.ovpn but for any obscur reason I am not able to access it after a reboot.
After a reboot, I have an address like: http://IP:8000//file.ovpn (The UUID disappeared)
I tried on two different OpenVPN VMs and same problem.

Many thanks for your help.

**Comment by QuentinPerez** [comment]
Hi @Digital14,

The SimpleHTTP is availabe only after the `client.ovpn` generation. https://github.com/scaleway-community/scaleway-openvpn/blob/master/overlay/etc/default/openvpn#L63-L71
If you reboot your server, the HTTP server will don't restart automatically and the `tmp` directory will be deleted. It's why you have a wrong URL. 😐

Also after a reboot you can find your `client.opvn` in `/root`

**Comment by multun** [comment]
fixed by 22c5aaf. You can now use:
```sh
$ scw-ovpn serve myprofile
```
To serve your config again.
