### ISSUE TITLE
Log file rotation

### ISSUE THREAD

**Issue by nlm** [scaleway-community/scaleway-openvpn#3]
The path you chose for the local log file (/var/log/openvpn-tcp443.log) will not be rotated by logrotate.

It's better to not provide this directive and let syslog do the job

```
# VPN logfile location
# If you don't specify a location here, logging will be done through
# syslogd and write to /var/log/messages
log-append /var/log/openvpn.log
```

**Comment by multun** [comment]
openvpn now logs to journald (22c5aaf)
