### ISSUE TITLE
Server Certificate Verification

### ISSUE THREAD

**Issue by IWriteThings** [scaleway-community/scaleway-openvpn#30]
Does anyone have a step by step guide to adding server certificate verification for this image? I have added all upgrades to my configuration in order to remove all warnings but this last one. Has any one else added server cert verification and if so, can you give me some steps? I tried following some online guides but it is out of date.

**Comment by multun** [comment]
The last image implements a fix:
https://github.com/scaleway-community/scaleway-openvpn/blob/master/overlay/usr/local/bin/scw-ovpn-show-client#L66

Thanks for reporting !
