### ISSUE TITLE
iptable: Permission denied (you must be root)

### ISSUE THREAD

**Issue by pierrepinon** [scaleway-community/scaleway-openvpn#34]
Hi,

Build process return "iptable: Permission denied (you must be root)" so iptable isn't loaded in openvpn image

Some docs about error : 
- https://github.com/moby/moby/issues/18230
- https://github.com/moby/moby/issues/4424

I will try to fix it soon

**Comment by multun** [comment]
I don't get it. Why would you need to run iptables inside docker ?
The current install process doesn't depend on iptables.
