### ISSUE TITLE
OpenVPN app -- can't connect on Lubuntu 15.04

### ISSUE THREAD

**Issue by tmatthews5511** [scaleway-community/scaleway-openvpn#5]
Hello, 

I created the server and then I downloaded the client.ovpn file in the /root directory. 

I did this -> sudo openvpn --config client.ovpn 

However, I could not connect. I received these errors: 

Sat Aug  8 14:52:32 2015 TLS_ERROR: BIO read tls_read_plaintext error: error:14082174:SSL routines:SSL3_CHECK_CERT_AND_ALGORITHM:dh key too small
Sat Aug  8 14:52:32 2015 TLS Error: TLS object -> incoming plaintext read error
Sat Aug  8 14:52:32 2015 TLS Error: TLS handshake failed

ta, t.

**Comment by moul** [comment]
Hi @tmatthews5511, thank you for reporting this issue, we will investigate

cc @nlm @aimxhaisse @achamo @edouardb

**Comment by moul** [comment]
Original issue: https://community.scaleway.com/t/openvpn-instantapp-cant-connect-to-the-server/902

**Comment by QuentinPerez** [comment]
Hello @tmatthews5511,

This error comes from openssl, error 14082174.
That's due to the [Logjam attack](https://weakdh.org/)
We have investigated your issue, but the actual solution is to craft a DH key 2048
The problem with this solution is that our CPU take ~25m to craft this key
So we looking for the better solutions, we are working on it :)

**Comment by deanperry** [comment]
I'm also having this issue on Mac

**Comment by QuentinPerez** [comment]
It was fixed with #6 but the new version is already on Scaleway ;)

**Comment by deanperry** [comment]
I've just created a new server but can't login using any OpenVPN client :/

**Comment by haarts** [comment]
Please note that there's a [bug](https://bugs.launchpad.net/ubuntu/+source/network-manager-openvpn/+bug/606365) in Gnome's network manager which prevents it from reading embedded keys etc.
There is supposedly a [workaround](http://askubuntu.com/questions/134918/setting-vpn-client) which requires you to extract the keys and paste them in their own files.

I tried that but to no avail. I'm left with the DH parameters and quite frankly I don't know what to do with them. The connection fails with a "Activation of network failed" message. I'm unsure why. `sudo journalctl -u NetworkManager` shows (and some other warnings):

    Sep 04 09:05:18 vuori NetworkManager[425]: <warn>  VPN connection 'scw-4187f9' connect timeout exceeded.

I had little luck with `sudo openvpn --config scw-4187f9.ovpn` either. I saw no apparent errors but neither did my network work afterward. I don't know exactly what I'm doing either, I took this approach from the aforementioned bug report on launchpad.

I'm using Arch, kernel 4.1.2.

**Comment by multun** [comment]
The bug was fixed upstream https://bugzilla.gnome.org/show_bug.cgi?id=633337
How about closing this issue ?
